### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by dR3b** [SaschaWillems/Vulkan#132]
On my "Arch Linux" machine, every demo fails with:
```
- segmentation fault (core dumped)  ./gears
```
```
Apr 15 18:59:18 obelix systemd-coredump[4423]: Process 4421 (gears) of user 1000 dumped core.
                                              
Stack trace of thread 4421:
#0  0x00007fa103e95833 n/a (libnvidia-glcore.so.364.16)
#1  0x0000000000410cfe _ZN7vkTools10loadShaderEPKcP10VkDevice_T21VkShaderStageFlagBits (gears)
#2  0x000000000040a29b _ZN17VulkanExampleBase10loadShaderENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE21VkShaderStageFlagBits (gears)
#3  0x0000000000407d43 _ZN13VulkanExample16preparePipelinesEv (gears)
#4  0x0000000000408f5c _ZN13

VulkanExample7prepareEv (gears)
#5  0x00000000004073e3 main (gears)
#6  0x00007fa105822710 __libc_start_main (libc.so.6)
#7  0x0000000000407649 _start (gears)
```

* OS: Arch Linux x86_64
* Kernel Release: 4.5.0-1-ARCH
* Type: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
* NVIDIA Driver Version: 364.16
* Server Vendor Version: 1.18.3 (11803000)
* GPUs: GeForce GTX 680 (GPU 0)

I have tested the precompiled binaries.

[gears-strace.txt](https://github.com/SaschaWillems/Vulkan/files/221412/gears-strace.txt)

**Comment by SaschaWillems** [comment]
Can you run the examples with validation enabled and see if the validation reports any errors? Did you put the data folder beside the binary folder?

**Comment by z3ntu** [comment]
Is your folder structure:
```
vulkan-examples
 - bin *(where bloom, computeparticles, etc resides)*
 - data *(where font.fnt, models/, etc resides)*
```
?

**Comment by dR3b** [comment]
@z3ntu 
Yes and today, after a reboot only "pushconstants" is crashing. All other demos are working now.
```
1440 segmentation fault (core dumped)  ./pushconstants
```
@SaschaWillems 
What do you mean with "Can you run the examples with validation"?

**Comment by 1ace** [comment]
At the top of every example, you'll see:

    #define ENABLE_VALIDATION false

The `triangle` example also includes an explanation:

    // Set to "true" to enable Vulkan's validation layers
    // See vulkandebug.cpp for details

**Comment by SaschaWillems** [comment]
On windows it's also possible to enable validation with a command line parameter. I'll add that to the linux code path in the future.

Please note that you need to have the LunarG Vulkan SDK installed in order to use the validation layers.

**Comment by z3ntu** [comment]
@dR3b `pushconstants` crashes for me too:

> ./pushconstants 
fish: “./pushconstants” terminated by signal SIGSEGV (Address boundary error)

**Comment by SaschaWillems** [comment]
@z3ntu : On what GPU? It won't run on my Intel (SandyBridge). I guess push constants are not yet implemented with the Mesa Intel Vulkan drivers.

**Comment by z3ntu** [comment]
GTX850M with Nvidia 364.16 driver, Arch Linux

**Comment by SaschaWillems** [comment]
Can you please run the examples with Validation enabled (requires an installed SDK) and see if the validation layers report any errors? The push constant samples run fine here on NVIDIA (980 and Shield) and AMD (R9 390).

**Comment by z3ntu** [comment]
So I installed `vulkan-validation-layers` with `pacman -S vulkan-validation-layers` (also installed `vulkan-headers`, set `#define ENABLE_VALIDATION true` in `pushconstants/pushconstants.cpp` recompiled, but I still get `fish: “./pushconstants” terminated by signal SIGSEGV (Address boundary error)` when launching.

**Comment by SaschaWillems** [comment]
In which line does the SIGSEGV occur? Can you step through the code?

**Comment by z3ntu** [comment]
How do I do this? I am just compiling it with cmake and running it in the terminal.

**Comment by z3ntu** [comment]
Apparently in https://github.com/SaschaWillems/Vulkan/blob/master/base/vulkanMeshLoader.hpp#L350

**Comment by z3ntu** [comment]
Debug info there:
![selection_041](https://cloud.githubusercontent.com/assets/3768500/14603883/ab418d5a-0570-11e6-883d-520f2f734087.png)

**Comment by SaschaWillems** [comment]
Thx for your effort. What's the ASSIMP version you're using? It seems that ASSIMP doesn't load the normals for that mesh, though it actually has normals (just checked).

**Comment by z3ntu** [comment]
assimp 3.2-2

**Comment by gqmelo** [comment]
I get the same problem. Only ```pushconstants``` is segfaulting. gdb backtrace is the same as the one cited by z3ntu

Running with strace, I found out the it is trying to open a missing ```samplescene.obj.mtl``` file:

```bash
$ strace ./pushconstants
   ...
open("./../data/models/samplescene.obj.mtl", O_RDONLY) = -1 ENOENT (No such file or directory)
   ...
open("./../data/models/samplescene.obj.mtl", O_RDONLY) = -1 ENOENT (No such file or directory)
```

This is the aiMesh struct values: 

```
paiMesh	const aiMesh *	0x9fa1b0	
	mPrimitiveTypes	unsigned int	2	
	mNumVertices	unsigned int	64	
	mNumFaces	unsigned int	32	
	mVertices	aiVector3D *	0x9fa6c0	
	mNormals	aiVector3D *	0x0	
	mTangents	aiVector3D *	0x0	
	mBitangents	aiVector3D *	0x0	
	mColors	aiColor4D *[8]	0x9fa1e0	
	mTextureCoords	aiVector3D *[8]	0x9fa220	
	mNumUVComponents	unsigned int [8]	0x9fa260	
	mFaces	aiFace *	0x9577d8	
	mNumBones	unsigned int	0	
	mBones	aiBone **	0x0	
	mMaterialIndex	unsigned int	0	
	mName	aiString	{...}	
	mNumAnimMeshes	unsigned int	0	
	mAnimMeshes	aiAnimMesh **	0x0	
```

System specs:

Ubuntu 16.04
GeForce GTX 950M
Driver 364.19

**Comment by SaschaWillems** [comment]
@gqmelo : That's odd as ASSIMP shouldn't fail if the .mtl file is missing (or at least does not for me). I have pushed a commit that uses the COLLADA version of the mesh instead of the .obj one.

Can you check again? Thx!

**Comment by z3ntu** [comment]
Yep, `pushconstants` does work now.

**Comment by gqmelo** [comment]
@SaschaWillems, now it is working for me too

**Comment by z3ntu** [comment]
@SaschaWillems `./computeparticles` still doesn't work (SIGSEGV)

**Comment by SaschaWillems** [comment]
@z3ntu : Instancing and multithreading fail because they can't load resources (texture and mesh). Is your data folder up-to-date?

Compute works fine for me on NVIDIA (GTX 980, Shield TV), AMD (R9 390) and Intel (Haswell, Linux).

**Comment by z3ntu** [comment]
Yep, I downloaded the data package again and extracted it. Binaries were compiled from the newest git source.

**Comment by SaschaWillems** [comment]
Where did you download? You need to get the current data directory from this repository.

I'll try to update the released binaries and data packages this weekend, but until then you need to compile and run from the repo.

**Comment by z3ntu** [comment]
Okay everything works now. Thanks.
